var scrollDelay=null;var saved_message_timeout=null;var SCROLL_AMOUNT=10;var SCROLL_SPEED=50;var SCROLL_THRESHOLD=35;var SCROLL_MULTIPLIER=3;var SCROLL_DECAY=7;var MOVING_THRESHOLD=10;function track_moveable_box(header_obj,container_obj,possible_wide,possible_narrow){this.possible_wide=possible_wide;this.possible_narrow=possible_narrow;this.listContainer=container_obj;this.headerObj=header_obj;this.listContainer.onmousedown=function(e){return this._onclick(e?e:window.event);}.bind(this);}
track_moveable_box.prototype._onclick=function(e){this.clickMouseY=mouseY(e);this.clickMouseX=mouseX(e);if(!is_left_click(e))return false;document.onselectstart=function(e){return false;};document.onmousemove=function(e){return this._track_move(e?e:window.event)}.bind(this);document.onmouseup=function(e){this._track_drop(e?e:window.event)}.bind(this);return false;}
track_moveable_box.prototype._track_move=function(e){if(Math.abs(mouseY(e)-this.clickMouseY)>MOVING_THRESHOLD||Math.abs(mouseX(e)-this.clickMouseX)>MOVING_THRESHOLD){var moveable=new moveable_box(this.listContainer,this.possible_wide,this.possible_narrow);moveable._onclick(null,this.clickMouseY,this.clickMouseX);this.headerObj.onclick=null;}}
track_moveable_box.prototype._track_drop=function(e){document.onmouseout=document.onmouseup=document.onmousemove=document.onclick=null;if(!this.headerObj.onclick){boxFlexToggle(this.listContainer);}}
function moveable_box(obj,possible_wide,possible_narrow){this.obj=obj;this.obj.possible_positions=new Array();this.obj.possible_positions['wide']=possible_wide;this.obj.possible_positions['narrow']=possible_narrow;this.obj.onmousedown=function(e){return this._onclick(e?e:window.event);}.bind(this);}
moveable_box.prototype._onclick=function(e,mouseY,mouseX){if(e&&!is_left_click(e))return false;document.moving_box=this;document.isScrolling=false;this.cols=new Array();this.cols['wide']=ge('moveable_wide');this.cols['narrow']=ge('moveable_narrow');this.cols_y=new Array();this.cols_y['wide']=new Array();this.cols_y['narrow']=new Array();this.cols_y['wide']['top']=elementY(this.cols['wide']);this.cols_y['narrow']['top']=elementY(this.cols['wide']);this.cols_y['wide']['bottom']=this.cols_y['wide']['top']+this.cols['wide'].offsetHeight;this.cols_y['narrow']['bottom']=this.cols_y['narrow']['top']+this.cols['narrow'].offsetHeight;if(elementX(this.cols['narrow'])<elementX(this.cols['wide'])){this.target_left="narrow";this.container_left="moveable_narrow";this.target_right="wide";this.container_right="moveable_wide";}else{this.target_left="wide";this.container_left="moveable_wide";this.target_right="narrow";this.container_right="moveable_narrow";}
this.dividers=null;this.dividers_y=null;this.more_sections=null;if(ge('hidden_apps_wide')||ge('hidden_apps_narrow')){this.has_hidden_sections=true;var wide_div=ge('more_apps_divider_wide');var narrow_div=ge('more_apps_divider_narrow');this.dividers={'wide':{'obj':wide_div,'y':0},'narrow':{'obj':narrow_div,'y':0}};this.more_sections=new Array();this.more_sections={'wide':ge('hidden_apps_wide'),'narrow':ge('hidden_apps_narrow')};this.empty_state={'wide':null,'narrow':null};this.is_unhideable_box=SPECIAL_APPS[this.obj.id.replace('box_app_','')];if(this.obj.parentNode.id.indexOf('hidden_apps_')!=-1){this.is_unhideable_box=false;}
if(this.is_unhideable_box){toggle_profile_apps_link(false,true);}
if(ge('toggle_boxes_link_content_narrow')&&!this.is_unhideable_box){var more_arrow=ge('toggle_boxes_link_content_narrow');if(more_arrow.style.display!='none'&&more_arrow.className=='see_more_arrow'){this.more_sections_expanded=false;}else{this.more_sections_expanded=true;}
for(var i=0;i<COLS_INDEX.length;i++){var col=COLS_INDEX[i];if(!this.more_sections[col].childNodes.length){this.dividers[col]['obj'].style.display='block';var hidden_state=create_hidden_section_empty_state();this.more_sections[col].parentNode.insertBefore(hidden_state,this.more_sections[col]);this.empty_state[col]=hidden_state;}}
if(this.more_sections_expanded){this._merge_display_more_section();}}}
this.obj.position=get_obj_coordinates(this.obj);this.obj.old_col_id=this.obj.parentNode.id;this.obj.handle=this.obj.childNodes[1];this.cur_col_id=this.obj.old_col_id;this.col_index=this.cur_col_id.replace('moveable_','');add_css_class_name(this.obj,'floating_box');add_css_class_name(this.obj,'explicit_width_'+this.cur_col_id);this.obj.style.top=this.obj.position['top']+'px';this.obj.style.left=this.obj.position['left']+'px';this.mouseOffsetY=(mouseY?mouseY:mouseY(e))-this.obj.position['top'];this.mouseOffsetX=(mouseX?mouseX:mouseX(e))-this.obj.position['left'];var childNodes=this.obj.childNodes;this.childNodesClassOld=new Array();for(var i=0;i<childNodes.length;i++){this.childNodesClassOld[i]=childNodes[i].className;if(childNodes[i].id!='box_handle'){childNodes[i].className+=' float_opacity';}}
this.placeholder=document.createElement('div');this.placeholder.id="placeholder";this.placeholder.className='placeholder ph_'+this.obj.parentNodeid;this.placeholder.style.height=(200<(this.obj.offsetHeight-15)?200:(this.obj.offsetHeight-15))+'px';this.obj.parentNode.insertBefore(this.placeholder,this.obj);this._color_placeholder(this.col_index);this.obj.parentNode.parentNode.appendChild(this.obj);this.elements_y_side_col=this._get_elements_y(this.target_left,this.obj);this.elements_y_main_col=this._get_elements_y(this.target_right,this.obj);this.elements_x_threshold=elementX(this.cols[this.target_right]);this._calculate_divider_y();document.onmousemove=function(e){return this._move(e?e:window.event,0,0)}.bind(this);document.onmouseup=function(e){this._drop()}.bind(this);return false;}
function create_hidden_section_empty_state(){var empty_state=document.createElement('div');empty_state.className='hidden_section_empty_state';empty_state.innerHTML=tx('mb03');return empty_state;}
function print_elements_y(elements_y)
{var output=null;for(var i=0;i<elements_y.length;i++)
if(elements_y[i]!=null)
output=output+' '+elements_y[i]['top'];else
output=output+' null';}
moveable_box.prototype._get_elements_y=function(column_id){var col=this.cols[column_id];var elements=new Array();for(var i=0;i<col.childNodes.length;i++){if(col.childNodes[i].id=="placeholder"){this.obj.cur_index=i;}
elements[i]=new Array();elements[i]['top']=elementY(col.childNodes[i]);elements[i]['bottom']=elements[i]['top']+col.childNodes[i].offsetHeight;}
return elements;}
moveable_box.prototype._move=function(e){if(e){this.obj.mouse_left=mouseX(e);this.obj.position=get_obj_coordinates(this.obj,mouseY(e)-this.mouseOffsetY,mouseX(e)-this.mouseOffsetX);}
var windowScroll=false;if(document.isScrolling){if(pageScrollY()>0||this.scrollYAmount>0){this.obj.position=get_obj_coordinates(this.obj,this.obj.position['top']+this.scrollYAmount,this.obj.position['left']+this.scrollXAmount);windowScroll=true;}}
this._calculate_placeholder();this.obj.style.top=this.obj.position['top']+'px';this.obj.style.left=this.obj.position['left']+'px';if(windowScroll){window.scrollBy(this.scrollXAmount,this.scrollYAmount);}
var scrollDown=false;var distance_from_top=this.obj.position['top']-pageScrollY();var distance_from_bottom=pageScrollY()+getViewportHeight()-this.obj.position['top'];if((scrollDown=distance_from_bottom<=SCROLL_THRESHOLD)||distance_from_top<=SCROLL_THRESHOLD){clearTimeout(scrollDelay);document.isScrolling=true;var distance_from_edge=scrollDown?distance_from_bottom:distance_from_top;distance_from_edge=distance_from_edge<0?0:distance_from_edge;var distance_fraction=(1-(distance_from_edge*1.0)/SCROLL_THRESHOLD);var scrollY=Math.round(SCROLL_AMOUNT+SCROLL_AMOUNT*SCROLL_MULTIPLIER*power(distance_fraction,SCROLL_DECAY));this.scrollXAmount=0;this.scrollYAmount=scrollDown?scrollY:-1*scrollY;scrollDelay=window.setTimeout(function(){if(document.isScrolling){document.moving_box._move(null);}},SCROLL_SPEED);}else{document.isScrolling=false;}}
function power(x,y){if(x==0){return 0;}
var power=1;for(var i=0;i<y;i++){power*=x;}
return power;}
moveable_box.prototype._calculate_placeholder=function(){if(this.obj.mouse_left<this.elements_x_threshold){if(this.placeholder.parentNode.id!=this.container_left){this._move_placeholder_to_other_column(this.target_left,this.elements_y_side_col);}else{this._move_placeholder_in_column(this.elements_y_side_col);}}else{if(this.placeholder.parentNode.id!=this.container_right){this._move_placeholder_to_other_column(this.target_right,this.elements_y_main_col);}else{this._move_placeholder_in_column(this.elements_y_main_col);}}}
moveable_box.prototype._calculate_divider_y=function(){if(this.has_hidden_sections){this.dividers['wide']['y']=elementY(this.dividers['wide']['obj']);this.dividers['narrow']['y']=elementY(this.dividers['narrow']['obj']);}}
moveable_box.prototype._move_placeholder_in_column=function(elements_y){var oldIndex=null;var childIndex=null;var upperBounds=null;var outOfBounds=false;var top=false;if(this.obj.cur_index<elements_y.length-1){var next_object_top=elements_y[this.obj.cur_index+1]['top'];next_object_threshold=elements_y[this.obj.cur_index+1]['bottom']-100;upperBounds=next_object_top>next_object_threshold?next_object_top:next_object_threshold;}
if(this.has_hidden_sections&&!this.more_sections_expanded&&!this.is_unhideable_box){if(this._should_expand_more_section()){toggle_profile_apps_link(true);this._merge_display_more_section();this.more_sections_expanded=true;this.dividers['wide']['obj'].style.display='block';this.dividers['narrow']['obj'].style.display='block';this.elements_y_side_col=this._get_elements_y(this.target_left,this.obj);this.elements_y_main_col=this._get_elements_y(this.target_right,this.obj);return;}}
if(upperBounds!=null&&this.obj.position['top']>upperBounds&&in_window_bounds(upperBounds,30)){oldIndex=this.obj.cur_index;this.obj.cur_index+=1;childIndex=this.obj.cur_index+1;}else
if(this.obj.cur_index>0&&this.obj.position['top']<elements_y[this.obj.cur_index-1]['top']+
Math.min(40,elements_y[this.obj.cur_index-1]['bottom']-elements_y[this.obj.cur_index-1]['top']-5)){oldIndex=this.obj.cur_index;this.obj.cur_index--;childIndex=this.obj.cur_index;}else
if((top=this.obj.position['top']<(elementY(this.placeholder.parentNode)-150))){var message=tx('mb01');display_error_message(this.obj,message,this.obj.position['top']);}else{hide(has_child(this.obj,'floating_error'));}
if(oldIndex!=null){if(this.obj.cur_index<elements_y.length-1){this.placeholder.parentNode.insertBefore(this.placeholder,this.placeholder.parentNode.childNodes[childIndex]);}else{this.placeholder.parentNode.appendChild(this.placeholder);}
if(this.has_hidden_sections){if(this.dividers[this.col_index]['obj'].previousSibling&&this.dividers[this.col_index]['obj'].previousSibling==this.placeholder){this._make_placeholder_blue();this._calculate_divider_y();}
if(this.dividers[this.col_index]['obj'].nextSibling&&this.dividers[this.col_index]['obj'].nextSibling==this.placeholder){this._make_placeholder_gray();var empty_state=this.empty_state[this.col_index];if(empty_state){empty_state.parentNode.removeChild(empty_state);this.empty_state[this.col_index]=null;}
this._calculate_divider_y();}}
var col=this.placeholder.parentNode;elements_y[oldIndex]=new Array();elements_y[oldIndex]['top']=elementY(col.childNodes[oldIndex]);elements_y[oldIndex]['bottom']=elements_y[oldIndex]['top']+col.childNodes[oldIndex].offsetHeight;elements_y[this.obj.cur_index]=new Array();elements_y[this.obj.cur_index]['top']=elementY(this.placeholder);elements_y[this.obj.cur_index]['bottom']=elements_y[this.obj.cur_index]['top']+this.placeholder.offsetHeight;}}
moveable_box.prototype._should_expand_more_section=function(){var more_apps_y=elementY(ge('toggle_profile_apps_link_'+this.col_index));var should_move=(this.obj.position.bottom>more_apps_y+100||this.obj.position.top+50>more_apps_y);return should_move;}
moveable_box.prototype.check_column_bounds=function(column){col=column.id.replace("moveable_","");if((this.obj.position['top']<this.cols_y[col]['top']-50)||(column.nextSibling&&this.obj.position['top']>this.cols_y[col]['bottom']-50)||(!column.nextSibling&&!in_window_bounds(this.cols_y[col]['bottom'],20))){return true;}
return false;}
function display_saved_message(message,xPos,yPos){var saved_message=document.createElement('div');saved_message.className='saved_message';saved_message.innerHTML=message;saved_message.style.left=xPos+'px';saved_message.style.top=yPos+'px';saved_message.id='floating_saved_message';$('content').appendChild(saved_message);}
function display_error_message(obj,message,obj_top){var error_message=false;if(!(error_message=has_child(obj,'floating_error'))){error_message=document.createElement('div');error_message.id='floating_error';obj.insertBefore(error_message,obj.firstChild);}
if(!in_window_bounds(obj_top,50)&&obj_top>=pageScrollY()+getViewportHeight()-50){error_message.className='floating_error error_above';}else{error_message.className='floating_error error_below';}
error_message.innerHTML=message;show(error_message);}
function in_window_bounds(top,window_offset){if(top>pageScrollY()+window_offset&&top<pageScrollY()+getViewportHeight()-window_offset)
return true;return false;}
moveable_box.prototype._color_placeholder=function(col_index){if(this.has_hidden_sections){for(var i=0;i<this.cols[col_index].childNodes.length;i++){if(this.cols[col_index].childNodes[i]==this.dividers[col_index]['obj']){this._make_placeholder_gray();return;}
if(this.cols[col_index].childNodes[i]==this.placeholder){this._make_placeholder_blue();return;}}}}
moveable_box.prototype._make_placeholder_blue=function(){add_css_class_name(this.placeholder,'placeholder_blue');remove_css_class_name(this.placeholder,'placeholder_gray');this.placeholder.innerHTML='';}
moveable_box.prototype._make_placeholder_gray=function(){remove_css_class_name(this.placeholder,'placeholder_blue');add_css_class_name(this.placeholder,'placeholder_gray');this.placeholder.innerHTML=tx('mb04');}
moveable_box.prototype._move_placeholder_to_other_column=function(column_id,elements_y){if(this.obj.possible_positions[column_id]!=true){display_error_message(this.obj,tx('mb02'),this.obj.position['top']);return;}
hide(has_child(this.obj,'floating_error'));var col=this.cols[column_id];var index=0;for(var i=0;i<elements_y.length;i++){if(this.obj.position['top']&&this.obj.position['top']<=elements_y[i]['top']){if(this.obj.position['top']+150<=elements_y[i]['top']||!in_window_bounds(elements_y[i]['top'],20)){if(i==0){display_error_message(this.obj,tx('mb01'),this.obj.position['top']);}
return;}
else
break;}else index++;}
if(index==0&&col.childNodes.length==0){var column_top=elementY(this.cols[column_id]);if(this.obj.position['top']<column_top-30)
return;}
var lastChildBottom=elements_y.length>0?elements_y[elements_y.length-1]['bottom']:column_top;if(index<elements_y.length){col.insertBefore(this.placeholder,col.childNodes[index]);}else{col.appendChild(this.placeholder);}
this.elements_y_side_col=this._get_elements_y(this.target_left,this.obj);this.elements_y_main_col=this._get_elements_y(this.target_right,this.obj);this.cur_col_id='moveable_'+column_id;this.col_index=column_id;if(this.has_hidden_sections){this._calculate_divider_y();this._color_placeholder(column_id);}}
function has_child(element,child_id){for(var i=0;i<element.childNodes.length;i++){if(element.childNodes[i].id==child_id){return element.childNodes[i];}}
return false;}
function get_type_from_id(col_id){return col_id.replace('moveable_','');}
moveable_box.prototype._merge_display_more_section=function(){this.cols['wide'].appendChild(this.dividers['wide']['obj']);this.cols['narrow'].appendChild(this.dividers['narrow']['obj']);while(this.more_sections['wide'].firstChild){this.cols['wide'].appendChild(this.more_sections['wide'].firstChild);}
while(this.more_sections['narrow'].firstChild){this.cols['narrow'].appendChild(this.more_sections['narrow'].firstChild);}}
moveable_box.prototype._drop=function(){document.isScrolling=false;var switched_cols=this.cur_col_id!=this.obj.old_col_id;var cur_col_type=get_type_from_id(this.cur_col_id);var placeholderYPos=elementY(this.placeholder)+40;var placeholderXPos=elementX(this.placeholder)+(this.placeholder.offsetWidth-130)/2;this.obj.style.width=this.cols[cur_col_type].offsetWidth+'px';if(switched_cols){this.obj.style.height=this.placeholder.offsetHeight+'px';var box_content=null;var header=null;for(var i=0;i<this.obj.childNodes.length;i++){if(this.obj.childNodes[i].id&&this.obj.childNodes[i].id.indexOf('box_subheader_')==0){header=this.obj.childNodes[i];}else if(this.obj.childNodes[i].id&&this.obj.childNodes[i].id.indexOf('app_content_')==0){box_content=this.obj.childNodes[i];}}
if(header)header.innerHTML="";box_content.innerHTML="Loading...";new AsyncRequest().setURI('/ajax/profile_boxes.php').setMethod('POST').setData({'profile_fbid':PROFILE_FBID,'app_id':this.obj.id,'new_col_type':cur_col_type}).setHandler(function(resp){this.markup=(resp.getPayload()).markup;if(!this.markup){return;}
this.obj.style.height=null;set_inner_html(this.obj,this.markup);this.obj.parentNode.replaceChild(this.obj.firstChild,this.obj);}.bind(this)).send();}
if(error_message=has_child(this.obj,'floating_error')){error_message.parentNode.removeChild(error_message);}
var childNodes=this.obj.childNodes;for(var i=0;i<childNodes.length;i++){childNodes[i].className=this.childNodesClassOld[i];}
this.obj.handle.className='handle_invisible';remove_css_class_name(this.obj,'floating_box')
this.obj.style.top=null;this.placeholder.parentNode.replaceChild(this.obj,this.placeholder);if(this.has_hidden_sections&&this.more_sections_expanded){for(col in this.empty_state){if(this.empty_state[col]){this.empty_state[col].parentNode.removeChild(this.empty_state[col]);this.empty_state[col]=null;}}
this._separate_display_more_section();this._reset_more_links();}
save_box_orders();document.moving_box=false;this.obj.onmousedown=null;document.onmouseout=document.onmouseup=document.onmousemove=window.onscroll=null;}
moveable_box.prototype._reset_more_links=function(){for(var i=0;i<COLS_INDEX.length;i++){if(this.more_sections[COLS_INDEX[i]].childNodes.length){show('toggle_profile_apps_link_'+COLS_INDEX[i]);}else{hide('toggle_profile_apps_link_'+COLS_INDEX[i]);this.dividers[COLS_INDEX[i]]['obj'].style.display='none';}}}
moveable_box.prototype._separate_display_more_section=function(){while(this.dividers['wide']['obj'].nextSibling){this.more_sections['wide'].appendChild(this.dividers['wide']['obj'].nextSibling);}
this.cols['wide'].parentNode.insertBefore(this.dividers['wide']['obj'],this.more_sections['wide']);while(this.dividers['narrow']['obj'].nextSibling){this.more_sections['narrow'].appendChild(this.dividers['narrow']['obj'].nextSibling);}
this.cols['narrow'].parentNode.insertBefore(this.dividers['narrow']['obj'],this.more_sections['narrow']);this.more_sections['narrow'].style.display='';this.more_sections['wide'].style.display='';}
function save_box_orders(){var moveable_wide=ge('moveable_wide');var hidden_wide=ge('hidden_apps_wide');var i,j;var moveable_wide_list='';for(i=0;i<moveable_wide.childNodes.length;i++){if(i!=0){moveable_wide_list+=':';}
moveable_wide_list+=moveable_wide.childNodes[i].id;}
var apps_wide_cutoff=i;if(hidden_wide){for(j=0;j<hidden_wide.childNodes.length;j++){if(i!=0){moveable_wide_list+=':';}
moveable_wide_list+=hidden_wide.childNodes[j].id;}}
var moveable_narrow=ge('moveable_narrow');var hidden_narrow=ge('hidden_apps_narrow');var moveable_narrow_list='';for(i=0;i<moveable_narrow.childNodes.length;i++){if(i!=0){moveable_narrow_list+=':';}
moveable_narrow_list+=moveable_narrow.childNodes[i].id;}
var apps_narrow_cutoff=i;if(hidden_narrow){for(j=0;j<hidden_narrow.childNodes.length;j++){if(i!=0){moveable_narrow_list+=':';}
moveable_narrow_list+=hidden_narrow.childNodes[j].id;}}
new AsyncRequest().setURI('/ajax/profile_boxes.php').setMethod('POST').setData({'profile_fbid':PROFILE_FBID,'moveable_wide_list':moveable_wide_list,'moveable_narrow_list':moveable_narrow_list,'apps_wide_cutoff':apps_wide_cutoff,'apps_narrow_cutoff':apps_narrow_cutoff}).send();}
function handle(obj,col_id,allow_both){if((obj.parentNode.parentNode.id=='moveable_narrow'||obj.parentNode.parentNode.id=='moveable_wide')&&!document.moving_box){this.obj=obj;var arrow_class=(allow_both?'movearrow':'updownarrow');this.obj.nextSibling.className='handle_'+col_id+' handle '+arrow_class;this.obj.onmouseout=function(e){return this._removearrow(e?e:window.event);}.bind(this);}}
handle.prototype._removearrow=function(){if(this.obj.parentNode.parentNode.id=='moveable_narrow'||this.obj.parentNode.parentNode.id=='moveable_wide')
this.obj.nextSibling.className='handle_invisible';}
function get_obj_coordinates(obj,y,x){if(y==null&&x==null){y=elementY(obj);x=elementX(obj);}
return{'top':y,'bottom':y+obj.offsetHeight,'left':x,'right':x+obj.offsetWidth};}
if(window.Bootloader){Bootloader.done(1);}